version: "3"
services:
  req-nginx:
    image: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./cert/c2.crt:/etc/nginx/certs/c2.crt:ro
      - ./cert/c2.key:/etc/nginx/certs/c2.key:ro
      - /opt/cdn:/opt/cdn/cdn

  req-mysql:
    image: mysql
    restart: always
    build: ./db
    environment:
      MYSQL_DATABASE: requestor_db
      MYSQL_USER: redteam
      MYSQL_PASSWORD: letredin
      MYSQL_ROOT_PASSWORD: letredin123!

  req-c2:
    build: ./c2
    restart: always
    environment:
      DATABASE_URL: mysql://redteam:letredin@req-mysql/requestor_db
      PWNBOARD_URL: http://pwnboard.win/pwn/boxaccess
      INIT_PASSWORD: letredin123!
      RESET_PASSWORD: letredin123!
      PWNBOARD_ENABLED: "false"
    depends_on:
      - req-mysql
