---
all:
  children:
    pfsense:
      vars:
        ansible_user: admin
        ansible_password: changeme
      children:
        routers:
          hosts:
            192.168.253.2:
            192.168.253.10:
            192.168.253.18:
            192.168.253.26:
            192.168.253.34:
            192.168.253.42:
            192.168.253.50:
            192.168.253.58:
            192.168.253.66:
            192.168.253.74:
            192.168.253.82:
            192.168.253.90:
            192.168.253.98:
            192.168.253.106:
    linux:
      vars:
        ansible_user: sysadmin
        ansible_password: changeme
        ansible_become_password: changeme
      children:
        ubuntu1:
          hosts:
            10.[1:14].1.10:
        ubuntu2:
          hosts:
            10.[1:14].1.40:
        web:
          hosts:
            10.[1:14].2.2:
        database:
          hosts:
            10.[1:14].2.3:
        dev:
          hosts:
            10.[1:14].2.10:
    windows:
      vars:
        ansible_connection: psrp
        ansible_psrp_cert_validation: ignore
        ansible_psrp_protocol: https
        ansible_psrp_auth: ntlm
        ansible_psrp_credssp_auth_mechanism: ntlm
        ansible_become_method: runas
      children: 
        ad:
          vars:
            ansible_user: "Administrator"
            ansible_password: "Change.me!"
            ansible_become_user: "Administrator"
            ansible_become_password: "Change.me!"
          hosts:
            10.[1:14].1.60:
        windows1:
          vars:
            ansible_user: ".\\Admin"
            ansible_password: "Change.me!"
            ansible_become_user: ".\\Admin"
            ansible_become_password: "Change.me!"
          hosts:
            10.[1:14].1.70:
        windows2:
          vars:
            ansible_user: ".\\Admin"
            ansible_password: "Change.me!"
            ansible_become_user: ".\\Admin"
            ansible_become_password: "Change.me!"
          hosts:
            10.[1:14].1.80:
        ftp:
          vars:
            ansible_user: "Administrator"
            ansible_password: "Change.me!"
            ansible_become_user: "Administrator"
            ansible_become_password: "Change.me!"
          hosts:
            10.[1:14].2.4:

    # team groups
    team01:
      vars:
        team_number: '01'
      hosts:
        192.168.253.2:
        10.1.1.10:
        10.1.1.40:
        10.1.2.2:
        10.1.2.3:
        10.1.2.10:
        10.1.1.60:
        10.1.1.70:
        10.1.1.80:
        10.1.2.4:
    team02:
      vars:
        team_number: '02'
      hosts:
        192.168.253.10:
        10.2.1.10:
        10.2.1.40:
        10.2.2.2:
        10.2.2.3:
        10.2.2.10:
        10.2.1.60:
        10.2.1.70:
        10.2.1.80:
        10.2.2.4:
    team03:
      vars:
        team_number: '03'
      hosts:
        192.168.253.18:
        10.3.1.10:
        10.3.1.40:
        10.3.2.2:
        10.3.2.3:
        10.3.2.10:
        10.3.1.60:
        10.3.1.70:
        10.3.1.80:
        10.3.2.4:
    team04:
      vars:
        team_number: '04'
      hosts:
        192.168.253.26:
        10.4.1.10:
        10.4.1.40:
        10.4.2.2:
        10.4.2.3:
        10.4.2.10:
        10.4.1.60:
        10.4.1.70:
        10.4.1.80:
        10.4.2.4:
    team05:
      vars:
        team_number: '05'
      hosts:
        192.168.253.34:
        10.5.1.10:
        10.5.1.40:
        10.5.2.2:
        10.5.2.3:
        10.5.2.10:
        10.5.1.60:
        10.5.1.70:
        10.5.1.80:
        10.5.2.4:
    team06:
      vars:
        team_number: '06'
      hosts:
        192.168.253.42:
        10.6.1.10:
        10.6.1.40:
        10.6.2.2:
        10.6.2.3:
        10.6.2.10:
        10.6.1.60:
        10.6.1.70:
        10.6.1.80:
        10.6.2.4:
    team07:
      vars:
        team_number: '07'
      hosts:
        192.168.253.50:
        10.7.1.10:
        10.7.1.40:
        10.7.2.2:
        10.7.2.3:
        10.7.2.10:
        10.7.1.60:
        10.7.1.70:
        10.7.1.80:
        10.7.2.4:
    team08:
      vars:
        team_number: '08'
      hosts:
        192.168.253.58:
        10.8.1.10:
        10.8.1.40:
        10.8.2.2:
        10.8.2.3:
        10.8.2.10:
        10.8.1.60:
        10.8.1.70:
        10.8.1.80:
        10.8.2.4:
    team09:
      vars:
        team_number: '09'
      hosts:
        192.168.253.66:
        10.9.1.10:
        10.9.1.40:
        10.9.2.2:
        10.9.2.3:
        10.9.2.10:
        10.9.1.60:
        10.9.1.70:
        10.9.1.80:
        10.9.2.4:
    team10:
      vars:
        team_number: '10'
      hosts:
        192.168.253.74:
        10.10.1.10:
        10.10.1.40:
        10.10.2.2:
        10.10.2.3:
        10.10.2.10:
        10.10.1.60:
        10.10.1.70:
        10.10.1.80:
        10.10.2.4:
    team11:
      vars:
        team_number: '11'
      hosts:
        192.168.253.82:
        10.11.1.10:
        10.11.1.40:
        10.11.2.2:
        10.11.2.3:
        10.11.2.10:
        10.11.1.60:
        10.11.1.70:
        10.11.1.80:
        10.11.2.4:
    team12:
      vars:
        team_number: '12'
      hosts:
        192.168.253.90:
        10.12.1.10:
        10.12.1.40:
        10.12.2.2:
        10.12.2.3:
        10.12.2.10:
        10.12.1.60:
        10.12.1.70:
        10.12.1.80:
        10.12.2.4:
    team13:
      vars:
        team_number: '13'
      hosts:
        192.168.253.98:
        10.13.1.10:
        10.13.1.40:
        10.13.2.2:
        10.13.2.3:
        10.13.2.10:
        10.13.1.60:
        10.13.1.70:
        10.13.1.80:
        10.13.2.4:
    team14:
      vars:
        team_number: '14'
      hosts:
        192.168.253.106:
        10.14.1.10:
        10.14.1.40:
        10.14.2.2:
        10.14.2.3:
        10.14.2.10:
        10.14.1.60:
        10.14.1.70:
        10.14.1.80:
        10.14.2.4: